# "Session/line number was not unique in database." error and Python code

This problem arises in the Jupyter Notebook cells when the cells have the same line number.
What you can do - if you are in Jupyter Notebook - is just restart the kernel.
The error will be solved.

![This is an image](Screen%20Shot%202022-03-16%20at%207.38.13%20pm.png)  
